select * from customers_details

-- 1. Total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as "Total Revenue" from customers_details
group by gender
order by "Total Revenue" desc

-- 2. customers who used discount but still spent more than the average purchase amount?

select customer_id, purchase_amount from customers_details
where purchase_amount >= (select avg(purchase_amount) from customers_details)

-- 3. Top 5 Products with the Highest Average Review Ratings?

select item_purchased as Product, round(avg(review_rating::numeric),2) as average_review_rating
from customers_details
group by item_purchased
order by average_review_rating desc
limit 5

-- 4. Comparing the average purchase amounts between the standard and express shipping.

select shipping_type as "Shipping Type", round(avg(purchase_amount),2) as average_purchase_amounts
from customers_details
where shipping_type in ('Standard','Express')
group by shipping_type
order by average_purchase_amounts desc

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status as "Subscription Status", round(avg(purchase_amount),2) as "Average Spending", sum(purchase_amount) as "Total Revenue"
from customers_details
group by subscription_status

-- 6. Which 5 products have the highest percentage of purchases with discount applied?

select item_purchased as "Products",
sum(100 * case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as "discount_rate"
from customers_details
group by item_purchased
order by "discount_rate" desc
limit 5

-- 7. Segmenting customers into 'New', 'Returning' and 'Loyal' based on their total number of purchases, 
-- and show the count of each segment.

with customer_type as (
select customer_id,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customers_details
)

select customer_segment, count(customer_id) as "Total Customers" from customer_type
group by customer_segment
order by "Total Customers" desc

-- 8. Top 3 purchased products within each category?

with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers_details
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders from item_counts
where item_rank <= 3

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status as "Subscription Status", 
count(customer_id) as "Total Customers" from customers_details
where previous_purchases > 5
group by subscription_status

-- 10. Revenue contribution of each age group?

select age_group as "Age Group", sum(purchase_amount) as "Total Revenue"
from customers_details
group by age_group
order by "Total Revenue" desc